siteUid: null
sortOrder: 15
template: /forms/bootstrap/submissions
uriParts:
  - forms/bootstrap/
  -
    - slug
    - '[^\/]+'
  - /submissions
uriPattern: 'forms/bootstrap/<slug:[^\/]+>/submissions'
