field: 0419cb8c-c0a4-41b9-bd68-52b17382ebb4 # Partners
fieldLayouts:
  e27b7ea7-be8f-4d98-a906-f45f16991724:
    tabs:
      -
        elements:
          -
            fieldUid: 08dfb538-829c-4b91-9e8a-a2a5fb05e527 # Fullname
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ebc68f43-f32f-496e-80e7-661e24c58290 # Partner Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d7eb751-fa4e-49c0-a085-68880412e022 # Partner Log
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0d7eb751-fa4e-49c0-a085-68880412e022: # Partner Log
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: partnerLogo
    instructions: ''
    name: 'Partner Log'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:89a77c27-74a4-4733-84cc-fb1bba1fe585' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89a77c27-74a4-4733-84cc-fb1bba1fe585' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  08dfb538-829c-4b91-9e8a-a2a5fb05e527: # Fullname
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fullname
    instructions: ''
    name: Fullname
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ebc68f43-f32f-496e-80e7-661e24c58290: # Partner Link
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: partnerLink
    instructions: ''
    name: 'Partner Link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: partners
name: Partners
sortOrder: 1
