field: 447027c2-9d54-4ee7-a3d4-31ca81a3ecb1 # socials
fieldLayouts:
  299f7d1c-1ad9-48f2-8997-445e3eebd13e:
    tabs:
      -
        elements:
          -
            fieldUid: 3038a8c1-571e-4032-8974-26d2f75064e8 # Platform Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 920ffc3d-58e8-40e2-a927-399517a452ba # Social link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5deff13c-64d0-4144-bb2a-312a4393745a # Social Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5deff13c-64d0-4144-bb2a-312a4393745a: # Social Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: socialImage
    instructions: ''
    name: 'Social Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:89a77c27-74a4-4733-84cc-fb1bba1fe585' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89a77c27-74a4-4733-84cc-fb1bba1fe585' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:89a77c27-74a4-4733-84cc-fb1bba1fe585' # Uploads
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  920ffc3d-58e8-40e2-a927-399517a452ba: # Social link
    columnSuffix: cmmhkmpr
    contentColumnType: string(255)
    fieldGroup: null
    handle: socialLink
    instructions: ''
    name: 'Social link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  3038a8c1-571e-4032-8974-26d2f75064e8: # Platform Name
    columnSuffix: rzhzqaek
    contentColumnType: string(240)
    fieldGroup: null
    handle: platformName
    instructions: ''
    name: 'Platform Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 60
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: socials
name: Socials
sortOrder: 1
