field: 7cae94da-dea4-43f7-a172-fdb7a9895ca8 # Testimonials
fieldLayouts:
  fd079f9b-c25c-4f2d-9dc9-cd5316c613ad:
    tabs:
      -
        elements:
          -
            fieldUid: 7fe7bdc9-f4e0-47fa-a831-82db591a36f3 # Full name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5c2322a9-1a7a-4489-b80c-bcea9c81af90 # testimonial Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 93469ed8-cb67-4c5c-8215-b158e212747e # testimonial Intro 
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5c2322a9-1a7a-4489-b80c-bcea9c81af90: # testimonial Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: testimonialImage
    instructions: ''
    name: 'testimonial Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:89a77c27-74a4-4733-84cc-fb1bba1fe585' # Uploads
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89a77c27-74a4-4733-84cc-fb1bba1fe585' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  7fe7bdc9-f4e0-47fa-a831-82db591a36f3: # Full name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fullName
    instructions: ''
    name: 'Full name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  93469ed8-cb67-4c5c-8215-b158e212747e: # testimonial Intro 
    columnSuffix: null
    contentColumnType: string(1020)
    fieldGroup: null
    handle: testimonialText
    instructions: ''
    name: 'testimonial Intro '
    searchable: false
    settings:
      byteLimit: null
      charLimit: 255
      code: ''
      columnType: null
      initialRows: '3'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: testimonials
name: Testimonials
sortOrder: 1
