fieldLayouts:
  cc73cc53-42d0-4322-96ec-d6b6d3c46da4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: d57375af-fd95-446c-9efb-ff9d08fb7951 # Hero title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 752f07aa-c77b-4050-970d-0ac239ce6c80 # Hero subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 28542e01-2582-4ce2-8f19-4bce5e2d7c14 # heroButton
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c39d048e-aca2-45c9-809c-421d40bf94c4 # Hero image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 2
      -
        elements:
          -
            fieldUid: f8189118-620a-43f9-90a8-ef38b4f1a021 # About Title 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c8305c00-1df8-4bd2-9257-2a1ea3f15de0 # AboutIntro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a559508-6b03-4139-8f98-19c82aaf7325 # AboutImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: About
        sortOrder: 3
      -
        elements:
          -
            fieldUid: ee654c2e-ccf3-4e37-95cd-43c47d4365af # Socials Intro 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 447027c2-9d54-4ee7-a3d4-31ca81a3ecb1 # socials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Socials
        sortOrder: 4
      -
        elements:
          -
            fieldUid: e2d2b645-10b9-42de-93d0-ce20320b878f # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0419cb8c-c0a4-41b9-bd68-52b17382ebb4 # Partners
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Partners
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 7f2c6124-eb0f-4ded-9c60-26adae2c9f0c # Testimonials Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b4651624-f962-4808-9a95-350b02a936ec # Testimonial Highlighted Name 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b9b18a69-579d-482c-9d06-e3d0f0f59b01 # Testimonial Highlighted Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b404755-5271-4148-8f5d-326e87f13a48 # testimonial Highlighted Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7cae94da-dea4-43f7-a172-fdb7a9895ca8 # Testimonials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Testimonials
        sortOrder: 6
      -
        elements:
          -
            fieldUid: e3038a78-b860-4e8b-9de0-dbb632d23cfc # Medium Title 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Mediums
        sortOrder: 7
      -
        elements:
          -
            fieldUid: d868cd7b-85cd-441e-be51-bb3663100dd8 # Stats Title 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Stats
        sortOrder: 8
handle: homepage
hasTitleField: false
name: Homepage
section: f401e857-8c7b-48ac-ada9-8f65ca666d4a # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
