fieldLayouts:
  cc73cc53-42d0-4322-96ec-d6b6d3c46da4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: d57375af-fd95-446c-9efb-ff9d08fb7951 # Hero title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 752f07aa-c77b-4050-970d-0ac239ce6c80 # Hero subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 28542e01-2582-4ce2-8f19-4bce5e2d7c14 # heroButton
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c39d048e-aca2-45c9-809c-421d40bf94c4 # Hero image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 123bac14-df85-4366-a03e-b91aa658b351 # Mediums Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 88afba06-2ca9-4b5c-91e8-34bb4e343b19 # Mediums
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Mediums
        sortOrder: 3
      -
        elements:
          -
            fieldUid: f8189118-620a-43f9-90a8-ef38b4f1a021 # About Title 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c8305c00-1df8-4bd2-9257-2a1ea3f15de0 # AboutIntro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a559508-6b03-4139-8f98-19c82aaf7325 # AboutImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: About
        sortOrder: 4
      -
        elements:
          -
            fieldUid: ee654c2e-ccf3-4e37-95cd-43c47d4365af # Socials Intro 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 447027c2-9d54-4ee7-a3d4-31ca81a3ecb1 # socials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Socials
        sortOrder: 5
handle: homepage
hasTitleField: false
name: Homepage
section: f401e857-8c7b-48ac-ada9-8f65ca666d4a # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
