allowPublicRegistration: true
defaultGroup: ''
photoSubpath: null
photoVolumeUid: 89a77c27-74a4-4733-84cc-fb1bba1fe585 # Uploads
requireEmailVerification: false
suspendByDefault: false
validateOnPublicRegistration: false
