tabs:
  -
    elements:
      -
        fieldUid: 055b4ea0-bead-4502-bef8-136324a6ed49 # Short description
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: description
    sortOrder: 1
