columnSuffix: qlcdqbdy
contentColumnType: text
fieldGroup: 0338e864-2b3a-445b-91e2-ed798b9ba31b # General
handle: intro
instructions: ''
name: Intro
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 89a77c27-74a4-4733-84cc-fb1bba1fe585 # Uploads
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
