columnSuffix: null
contentColumnType: string
fieldGroup: a336ca38-fd77-4465-8172-7e76669ea403 # Mediums
handle: mediums
instructions: ''
name: Mediums
searchable: false
settings:
  contentTable: '{{%matrixcontent_mediums}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
