columnSuffix: null
contentColumnType: string
fieldGroup: 0338e864-2b3a-445b-91e2-ed798b9ba31b # General
handle: menu
instructions: ''
name: Menu
searchable: false
settings:
  contentTable: '{{%matrixcontent_menu}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
