columnSuffix: xopgliek
contentColumnType: text
fieldGroup: b9c68e31-af36-42a3-a6ef-ae929d803505 # Assigments
handle: shortDescription
instructions: ''
name: 'Short description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
