dateModified: 1641431875
email:
  fromEmail: paranormaxniels@gmail.com
  fromName: paranormax
  replyToEmail: null
  template: ''
  transportSettings:
    password: 'vef-BNF*qdc6rft2rnd'
    timeout: '10'
    username: paranormaxniels@gmail.com
  transportType: craft\mail\transportadapters\Gmail
meta:
  __names__:
    0a559508-6b03-4139-8f98-19c82aaf7325: AboutImage # AboutImage
    0d7eb751-fa4e-49c0-a085-68880412e022: 'Partner Log' # Partner Log
    1d516ff2-714f-46d2-9cb4-2f6df535a61c: New # New
    1f7e54e6-a0c3-4c13-9628-82f831ea8664: Date # Date
    2f52df08-fd1b-45f1-86de-8a6513355941: paranormax # paranormax
    3d2769a4-1306-4626-948f-8a4fb8096765: longDescription # longDescription
    3f2a0ec6-dde7-4cc8-9f9e-53b97721984d: 'Assigment Image' # Assigment Image
    5deff13c-64d0-4144-bb2a-312a4393745a: 'Social Image' # Social Image
    6d8e3673-e879-4c23-9bda-6277baa77d95: 'Full Name' # Full Name
    7b2086fd-9923-4004-a271-fd82dd752781: 'Main image' # Main image
    08dfb538-829c-4b91-9e8a-a2a5fb05e527: Fullname # Fullname
    9da56d12-3869-42e3-8b17-4e298c8b5f7f: 'Contact Form' # Contact Form
    9e77f2bb-3de8-4c3e-b6bb-31e5367c9adc: paranormax # paranormax
    26c65efd-5ee8-452f-a8dc-a8c1ef35b9d8: 'Short description' # Short description
    36f222a3-dc9a-4b2a-be51-a657891fd8ba: Homepage # Homepage
    055b4ea0-bead-4502-bef8-136324a6ed49: 'Short description' # Short description
    56c2fd1d-2a17-49a9-bb54-75395f9d11ee: Partners # Partners
    74d6daf7-e2ed-4347-bbf2-bebe14ed7425: Footer # Footer
    76c62145-f4a9-48f9-8023-889655f124ee: 'Privacy Policy' # Privacy Policy
    77d7adb5-9953-4236-b115-c50673563aea: New # New
    89a77c27-74a4-4733-84cc-fb1bba1fe585: Uploads # Uploads
    89b15cc2-16c9-411c-a5e0-987b6b2b9639: Mediums # Mediums
    275a2c43-f3fb-4d38-a696-8012131ff331: Default # Default
    306a9a21-248b-46d2-899f-070f6b159055: Status # Status
    0338e864-2b3a-445b-91e2-ed798b9ba31b: General # General
    0419cb8c-c0a4-41b9-bd68-52b17382ebb4: Partners # Partners
    752f07aa-c77b-4050-970d-0ac239ce6c80: 'Hero subtitle' # Hero subtitle
    753ee6e9-0d3e-4bbd-91dc-6593f9a5c2e0: Socials # Socials
    920ffc3d-58e8-40e2-a927-399517a452ba: 'Social link' # Social link
    3038a8c1-571e-4032-8974-26d2f75064e8: 'Platform Name' # Platform Name
    28542e01-2582-4ce2-8f19-4bce5e2d7c14: heroButton # heroButton
    447027c2-9d54-4ee7-a3d4-31ca81a3ecb1: socials # socials
    868543fd-a092-4e33-9b3e-184bb8214998: footer # footer
    8510118e-a94c-474b-8c99-c7582f771711: 'Contact Form' # Contact Form
    a06667e8-9b29-43e0-a233-3a2df2b65891: 'Medium Image' # Medium Image
    a2f0fc69-150d-4d85-b00e-cd0941c12caf: 'Status Assigments' # Status Assigments
    a9c9fdac-1294-4d72-baf5-e282193b78d6: Partners # Partners
    a69e96c7-e41e-40d8-b130-c18b4572dc39: Image # Image
    a336ca38-fd77-4465-8172-7e76669ea403: Mediums # Mediums
    af96a360-e868-4b44-96c7-1f59862c15ac: New # New
    b00d2209-fc75-4d18-81e9-e911fb01b478: 'Medium description' # Medium description
    b9c68e31-af36-42a3-a6ef-ae929d803505: Assigments # Assigments
    b9ea63f3-6f07-4bf8-9b3c-794d00de390a: About # About
    ba1001c3-692c-411a-8318-cf158f47cf71: 'MediumSkills ' # MediumSkills 
    c39d048e-aca2-45c9-809c-421d40bf94c4: 'Hero image' # Hero image
    c60eeba3-1524-4c73-b4e0-f26aa4d1957e: Assigments # Assigments
    c8305c00-1df8-4bd2-9257-2a1ea3f15de0: AboutIntro # AboutIntro
    ce98cc55-b67b-4086-a132-4af940e1aa99: 'Long Description' # Long Description
    d57375af-fd95-446c-9efb-ff9d08fb7951: 'Hero title' # Hero title
    dcb8c327-7be6-4722-a756-439adbc78f92: Home # Home
    e2d2b645-10b9-42de-93d0-ce20320b878f: Intro # Intro
    e691f341-1d87-4695-ba4a-b2bd2d47cdd1: Socials # Socials
    e787970d-0f13-47a1-a405-b0f17adb892d: Default # Default
    ebc68f43-f32f-496e-80e7-661e24c58290: 'Partner Link' # Partner Link
    ed6c8077-664c-4ab5-8aef-90d044ce2e7e: 'Contact Form' # Contact Form
    ee654c2e-ccf3-4e37-95cd-43c47d4365af: 'Socials Intro ' # Socials Intro 
    ef98329f-cbaf-4fd1-b69d-27e839d414a7: Disclaimer # Disclaimer
    f401e857-8c7b-48ac-ada9-8f65ca666d4a: Homepage # Homepage
    f8189118-620a-43f9-90a8-ef38b4f1a021: 'About Title ' # About Title 
plugins:
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: lite
    enabled: true
    licenseKey: GT4X09XOT5BRPTVSJMLERW88
    schemaVersion: 3.5.1
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: null
      autoScroll: true
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      clientDigestFrequency: 1
      clientDigestRecipients: null
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: submissions
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: null
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: ''
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: flexbox.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: ''
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: null
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: true
      removeNewlines: ''
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: false
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: '1'
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: paranormax
  retryDuration: null
  schemaVersion: 3.7.8
  timeZone: Europe/Brussels
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
